### ISSUE TITLE
Change description to use .org domain name

### ISSUE THREAD

**Issue by thehonkinggoose** [freeCodeCamp/fcc-github-syncing-service#1]
> "A prototype for a service freeCodeCamp can use to sync camper progress between GitHub and freeCodeCamp.com"

Should be "A prototype for a service freeCodeCamp can use to sync camper progress between GitHub and freeCodeCamp.org" to reflect freeCodeCamp's new domain name.

**Comment by AndrewWalsh** [comment]
Sounds good to me - interested in submitting a PR? If so, please replace the entire README.md with your sentence, as it's outdated.

**Comment by thehonkinggoose** [comment]
I did PR for README. I'm taking about description at the top. Only maintainers can adjust it :/

**Comment by AndrewWalsh** [comment]
Ah ok - can't see your PR though

**Comment by thehonkinggoose** [comment]
@AndrewGHC Opps forgot the click propose. See: https://github.com/freeCodeCamp/fcc-github-syncing-service/pull/2

**Comment by AndrewWalsh** [comment]
Cheers!

Edit: A maintainer e.g. @QuincyLarson might need to change the description

**Comment by QuincyLarson** [comment]
@AndrewGHC @nsuchy I've updated the project description on GitHub :)
